/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDonateRouteImport } from './routes/api.donate'
import { Route as ApiTranslateTokenRouteImport } from './routes/api.translate-token'
import { Route as ApiTranslationLanguagesRouteImport } from './routes/api.translation-languages'
import { Route as MeetRoomRouteImport } from './routes/meet.$room'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonateRoute = ApiDonateRouteImport.update({
  id: '/api/donate',
  path: '/api/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateTokenRoute = ApiTranslateTokenRouteImport.update({
  id: '/api/translate-token',
  path: '/api/translate-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslationLanguagesRoute = ApiTranslationLanguagesRouteImport.update({
  id: '/api/translation-languages',
  path: '/api/translation-languages',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoomRoute = MeetRoomRouteImport.update({
  id: '/meet/$room',
  path: '/meet/$room',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/donate': typeof ApiDonateRoute
  '/api/translate-token': typeof ApiTranslateTokenRoute
  '/api/translation-languages': typeof ApiTranslationLanguagesRoute
  '/meet/$room': typeof MeetRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/donate': typeof ApiDonateRoute
  '/api/translate-token': typeof ApiTranslateTokenRoute
  '/api/translation-languages': typeof ApiTranslationLanguagesRoute
  '/meet/$room': typeof MeetRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/donate': typeof ApiDonateRoute
  '/api/translate-token': typeof ApiTranslateTokenRoute
  '/api/translation-languages': typeof ApiTranslationLanguagesRoute
  '/meet/$room': typeof MeetRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/donate'
    | '/api/translate-token'
    | '/api/translation-languages'
    | '/meet/$room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/donate'
    | '/api/translate-token'
    | '/api/translation-languages'
    | '/meet/$room'
  id:
    | '__root__'
    | '/'
    | '/api/donate'
    | '/api/translate-token'
    | '/api/translation-languages'
    | '/meet/$room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDonateRoute: typeof ApiDonateRoute
  ApiTranslateTokenRoute: typeof ApiTranslateTokenRoute
  ApiTranslationLanguagesRoute: typeof ApiTranslationLanguagesRoute
  MeetRoomRoute: typeof MeetRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donate': {
      id: '/api/donate'
      path: '/api/donate'
      fullPath: '/api/donate'
      preLoaderRoute: typeof ApiDonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate-token': {
      id: '/api/translate-token'
      path: '/api/translate-token'
      fullPath: '/api/translate-token'
      preLoaderRoute: typeof ApiTranslateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translation-languages': {
      id: '/api/translation-languages'
      path: '/api/translation-languages'
      fullPath: '/api/translation-languages'
      preLoaderRoute: typeof ApiTranslationLanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet/$room': {
      id: '/meet/$room'
      path: '/meet/$room'
      fullPath: '/meet/$room'
      preLoaderRoute: typeof MeetRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDonateRoute: ApiDonateRoute,
  ApiTranslateTokenRoute: ApiTranslateTokenRoute,
  ApiTranslationLanguagesRoute: ApiTranslationLanguagesRoute,
  MeetRoomRoute: MeetRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
